-- PostgreSQL Schema for Kannaya Electrical ERP with Dynamic Categories & Role Access

DO $$ BEGIN
    CREATE TYPE "PaymentMethod" AS ENUM ('CASH', 'UPI', 'CARD', 'CREDIT', 'SPLIT');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "LedgerType" AS ENUM ('SALE', 'PAYMENT', 'PURCHASE', 'RETURN', 'ADJUSTMENT');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "Role" AS ENUM ('ADMIN', 'STAFF');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS "User" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT UNIQUE NOT NULL,
  "password" TEXT NOT NULL,
  "pinCode" TEXT DEFAULT '1234',
  "role" "Role" NOT NULL DEFAULT 'STAFF',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Category" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT UNIQUE NOT NULL,
  "description" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Brand" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT UNIQUE NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Rack" (
  "id" TEXT PRIMARY KEY,
  "rackName" TEXT NOT NULL,
  "shelfCode" TEXT NOT NULL,
  "description" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Rack_rackName_shelfCode_key" UNIQUE ("rackName", "shelfCode")
);

CREATE TABLE IF NOT EXISTS "Product" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "sku" TEXT UNIQUE,
  "barcode" TEXT UNIQUE NOT NULL,
  "hsnCode" TEXT DEFAULT '8544',
  "gstPercent" DOUBLE PRECISION NOT NULL DEFAULT 18,
  "unit" TEXT NOT NULL,
  "purchasePrice" DOUBLE PRECISION NOT NULL,
  "sellingPrice" DOUBLE PRECISION NOT NULL,
  "wholesalePrice" DOUBLE PRECISION,
  "minWholesaleQty" DOUBLE PRECISION,
  "stockQuantity" DOUBLE PRECISION NOT NULL,
  "minStockAlert" DOUBLE PRECISION NOT NULL,
  "warranty" TEXT,
  "description" TEXT,
  "categoryId" TEXT NOT NULL REFERENCES "Category"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "brandId" TEXT NOT NULL REFERENCES "Brand"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "rackId" TEXT REFERENCES "Rack"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Customer" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "phone" TEXT UNIQUE NOT NULL,
  "email" TEXT,
  "address" TEXT,
  "creditLimit" DOUBLE PRECISION NOT NULL DEFAULT 50000,
  "totalPurchases" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "totalPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "outstanding" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Supplier" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "contactPerson" TEXT,
  "phone" TEXT UNIQUE NOT NULL,
  "email" TEXT,
  "address" TEXT,
  "totalPurchased" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "totalPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "outstanding" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Invoice" (
  "id" TEXT PRIMARY KEY,
  "invoiceNo" TEXT UNIQUE NOT NULL,
  "customerId" TEXT REFERENCES "Customer"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "customerName" TEXT NOT NULL,
  "customerPhone" TEXT NOT NULL,
  "subtotal" DOUBLE PRECISION NOT NULL,
  "discount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "tax" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "totalAmount" DOUBLE PRECISION NOT NULL,
  "paidAmount" DOUBLE PRECISION NOT NULL,
  "dueAmount" DOUBLE PRECISION NOT NULL,
  "paymentMethod" "PaymentMethod" NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'COMPLETED',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "InvoiceItem" (
  "id" TEXT PRIMARY KEY,
  "invoiceId" TEXT NOT NULL REFERENCES "Invoice"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "productId" TEXT NOT NULL REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "productName" TEXT NOT NULL,
  "unit" TEXT NOT NULL,
  "price" DOUBLE PRECISION NOT NULL,
  "quantity" DOUBLE PRECISION NOT NULL,
  "total" DOUBLE PRECISION NOT NULL,
  "rackLocation" TEXT
);

CREATE TABLE IF NOT EXISTS "CustomerLedger" (
  "id" TEXT PRIMARY KEY,
  "customerId" TEXT NOT NULL REFERENCES "Customer"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "type" "LedgerType" NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "balance" DOUBLE PRECISION NOT NULL,
  "notes" TEXT,
  "invoiceId" TEXT REFERENCES "Invoice"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "PurchaseOrder" (
  "id" TEXT PRIMARY KEY,
  "poNumber" TEXT UNIQUE NOT NULL,
  "supplierId" TEXT NOT NULL REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "totalAmount" DOUBLE PRECISION NOT NULL,
  "paidAmount" DOUBLE PRECISION NOT NULL,
  "dueAmount" DOUBLE PRECISION NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'RECEIVED',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "PurchaseOrderItem" (
  "id" TEXT PRIMARY KEY,
  "purchaseOrderId" TEXT NOT NULL REFERENCES "PurchaseOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "productId" TEXT NOT NULL REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "price" DOUBLE PRECISION NOT NULL,
  "quantity" DOUBLE PRECISION NOT NULL,
  "total" DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS "SupplierLedger" (
  "id" TEXT PRIMARY KEY,
  "supplierId" TEXT NOT NULL REFERENCES "Supplier"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "type" "LedgerType" NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "balance" DOUBLE PRECISION NOT NULL,
  "notes" TEXT,
  "purchaseOrderId" TEXT REFERENCES "PurchaseOrder"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ShopSettings" (
  "id" TEXT PRIMARY KEY DEFAULT 'default',
  "shopName" TEXT NOT NULL DEFAULT 'VENKATA LAKSHMI ELECTRONICS',
  "tagline" TEXT NOT NULL DEFAULT 'Complete Electrical & Hardware Solutions',
  "phone" TEXT NOT NULL DEFAULT '+91 98765 43210',
  "email" TEXT DEFAULT 'info@venkatalakshmi.com',
  "address" TEXT NOT NULL DEFAULT 'Shop #12-4, Main Market Road, Near Town Clock Tower, City - 500001',
  "gstin" TEXT NOT NULL DEFAULT '36ABCDE1234F1Z5',
  "printerType" TEXT NOT NULL DEFAULT '80mm',
  "defaultGstPercent" DOUBLE PRECISION NOT NULL DEFAULT 18,
  "defaultHsnCode" TEXT NOT NULL DEFAULT '8544',
  "termsConditions" TEXT NOT NULL DEFAULT 'Goods once sold will not be taken back or exchanged. Subject to local jurisdiction.',
  "bankDetails" TEXT DEFAULT 'State Bank of India A/C: 1234567890 | IFSC: SBIN0001234',
  "upiId" TEXT DEFAULT '9876543210@paytm',
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
